### PR TITLE
Fix/issue 41

### LINKED ISSUE #41: assign_test_ids may overwrite text outside of of test_that context
In this example, the tests were named "png" and "bmp". The devices were also replaced given that the text was identical:
image

In this circumstance, it also replaced the device in other test files:
image

Im not sure whether it makes sense to fix this "bug" or not. In my opinion I think we should opt to have more detailed test names, as this is a very specific circumstance that wouldn't arise often

### PR DESCRIPTION
**Pull request by barrettk**
This PR is mainly to fix issue #41. However, additional changes may follow that make converting packages yspec, mrgsolve, pmplots, pmtables, mrggsave, and templ, to yaml stories easier and with less manual manipulation.

So far 2 new function arguments have been added

closes #41

### CODE REVIEW

**Comment by barrettk** [comment]
Added a new function argument that makes manually adding more tests easier, by allowing users to return the warning messages. Here's one use case:
```
missed_tests <- milestone_to_test_id(stories_df = stories_df, tests = test_ids, return_warnings = TRUE)$missing_milestones
missed_tests %>% dplyr::count(TestFile) %>% dplyr::arrange(desc(n))
```

image

**Comment by barrettk** [comment]
There are likely to be additional changes to the function when we tackle mrgsolve. Not sure if we want to pile them up on this PR, or create new ones as issues arise.

File: R/assign-test-ids.R [hunk 1]
```diff
@@ -67,14 +70,16 @@ assign_test_ids <- function(
 #' @param stories_df a dataframe of stories returned by `parse_github_issues()`.
 #' @param tests dataframe returned by [assign_test_ids()]
 #'        Must have the following column names: "TestNames", "TestIds"
+#' @param return_warnings logical (T/F). Whether or not to return the warning messages as well.
```
Comment (kyleam) [inline R/assign-test-ids.R:73]: Hmm, this is confusingly worded.  You're not returning warning messages, you're returning the missing IDs and missing milestones that the warning messages were about.

File: R/assign-test-ids.R [hunk 2]
```diff
@@ -8,21 +8,24 @@
...
 #' @param overwrite (T/F) whether or not to overwrite test files with new test ids
+#' @param start_after integer. Desired starting point for test ids; must be greater than or equal to 1.
 #'
 #' @importFrom dplyr mutate distinct
 #' @importFrom testthat find_test_scripts
 #' @importFrom stringr str_pad
 #' @importFrom purrr map flatten_chr
 #' @importFrom tibble tibble
-#' @importFrom checkmate assert_string
+#' @importFrom checkmate assert_string checkIntegerish
```
Comment (kyleam) [inline R/assign-test-ids.R:18]: nit: you're using the `assert_string` spelling rather than `assertString` (good), so for consistency use `check_integerish` rather than `checkIntegerish`

File: R/assign-test-ids.R [hunk 3]
```diff
@@ -8,21 +8,24 @@
...
 #' @export
 assign_test_ids <- function(
   prefix,
   test_path = getOption("mrgvalprep.TEST_LOC"),
-  overwrite = TRUE)
+  overwrite = TRUE,
+  start_after = 1)
```
Comment (kyleam) [inline R/assign-test-ids.R:24]: "after" seems like a misleading way to name it given that the generated test IDs will _include_ the value.

File: R/assign-test-ids.R [hunk 4]
```diff
@@ -116,25 +121,43 @@ milestone_to_test_id <- function(stories_df, tests){
...
 
 }
 
 #' Reads and returns all tests from test files
 #' @importFrom purrr discard
 #' @importFrom stringr str_trim str_match
 #'
-#' @param lines character vector. Output of `readLines()` for a single test
+#' @param lines character vector. Output of `readLines()` for a single test.
+#' @param full_string logical. Whether or not to return the test_that call surrounding the test name .
```
Comment (kyleam) [inline R/assign-test-ids.R:143]: spurious space before trailing period

File: R/assign-test-ids.R [hunk 5]
```diff
@@ -116,25 +121,43 @@ milestone_to_test_id <- function(stories_df, tests){
...
-parse_tests <- function(test_file) {
+parse_tests <- function(test_file, full_string = FALSE) {
   lines <- readLines(test_file)
   re <- "^ *(?:test_that|it) *\\( *(['\"])(?<name>.*)\\1 *, *(?:\\{ *)?$"
-  tmp <- str_match(lines, re) %>%
-    `[`(, "name") %>%
-    discard(is.na) %>%
-    str_trim(side = "both")
-  setNames(tmp, rep(basename(test_file), length(tmp)))
+  if(full_string){
```
Comment (kyleam) [inline R/assign-test-ids.R:149]: This `full_string` branch is the largest part of this diff and then never used.  If it's a false start or not relevant at this point, please drop it.

File: R/assign-test-ids.R [hunk 6]
```diff
@@ -206,10 +229,12 @@ print_and_capture <- function(x)
 #'
 #' @importFrom stringi stri_replace_all_regex
 #' @keywords internal
+
```
Comment (kyleam) [inline R/assign-test-ids.R:232]: nit: please drop unconventional blank line between the test name and docstring

File: R/assign-test-ids.R [hunk 7]
```diff
@@ -206,10 +229,12 @@ print_and_capture <- function(x)
...
 replace_test_str <- function(test_file, from, to){
-  from <- paste0("(['\"] *\\Q", from, "\\E)( *['\"])")
+  from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *['\"])")
```
Comment (kyleam) [inline R/assign-test-ids.R:234]: Here's this new diff and the one from `parse_tests` side by side (with `...` indicating the pasted in `from`):

```
replace_test_str  ^( *(?:test_that|it) *\\( *['\"] *\\Q...\\E)( *['\"])
parse_tests       ^ *(?:test_that|it) *\\( *(['\"])(?<name>.*)\\1 *, *(?:\\{ *)?$
```

Ideally this would be reworked so that there wouldn't be near-duplicate regexs, but this fix isn't really introducing that issue (just making it more obvious).  So I think that's fine to leave that be.

However, I do think if you're going to have near-duplicate regexs, you might as well eliminate all unnecessary differences between them.

Here's the ones I spot:

 * `parse_tests` is more correct in that it matches the delimiter (the `\\1` after the `name` group)

 * `parse_tests` anchors the string at the end (` *, *(?:\\{ *)?$`).  Given that `replace_test_str` is receiving names originally extracted by `replace_test_str`, I don't see a reason to have it not use the same anchor.

So my (untested) suggestion is that `replace_test_str` uses a regex like this:

```
from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *\\1 *, *(?:\\{ *)?)$")
```

**Review by kyleam — CHANGES_REQUESTED** [review]
I see the following test failures:

```
── Error (test-end-to-end.R:38:3): Github end-to-end works ─────────────────────
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. └─mrgvalprep::parse_github_issues(...) at test-end-to-end.R:38:2
 2.   └─checkmate::assert_string(prefix)
── Error (test-parse-github-issues.R:5:3): parse_github_issues() pulls from Github ──
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. └─mrgvalprep::parse_github_issues(...) at test-parse-github-issues.R:5:2
 2.   └─checkmate::assert_string(prefix)
── Error (test-stories-to-yaml.R:37:3): stories_to_yaml() works correctly with github issues ──
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. ├─... %>% ... at test-stories-to-yaml.R:37:2
 2. ├─mrgvalprep::stories_to_yaml(., file = file.path(tempdir(), "temp.yaml"))
 3. │ └─sheet_df %>% ...
 4. ├─dplyr::mutate(., TestIds = sapply(.data$TestIds, toString))
 5. └─mrgvalprep::parse_github_issues(...)
 6.   └─checkmate::assert_string(prefix)

[ FAIL 3 | WARN 0 | SKIP 1 | PASS 133 ]
Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 2 notes ✖
Error: R CMD check found ERRORs
Execution halted
```

(And ideally the fix for gh-41 would come with a test.)

**Comment by kyleam** [comment]
> Not sure if we want to pile them up on this PR, or create new ones as issues arise.

Please create dedicated PRs.

File: R/assign-test-ids.R (hunk 7 above)
Comment (kyleam) [reply R/assign-test-ids.R:234]: I'll mark this as resolved since this comment just ends up being a "reading aloud" comment.

File: R/assign-test-ids.R (hunk 5 above)
Comment (barrettk) [reply R/assign-test-ids.R:149]: I did this to correct for a previous bug, bug then it ended up not being necessary. Part of me wanted to keep it in case I needed it later, though I guess I could always add it back if need be

Comment (kyleam) [reply R/assign-test-ids.R:149]: Look at it from the standpoint of a reviewer trying to understand a changeset or you coming back to the code later. 
 Leaving unused cruft around just invites confusion.

File: NAMESPACE [hunk 8]
```diff
@@ -13,6 +13,7 @@ export(read_spec_yaml)
 export(stories_to_yaml)
 export(validate_tests)
 importFrom(checkmate,assert_string)
+importFrom(checkmate,check_integerish)
```
Comment (kyleam) [inline NAMESPACE:16]: It looks like you must have mistakenly edited this by hand.  `checkIntegerish` is still used in `assign_test_ids`.

```
$ git show --oneline -s
6e72efc (HEAD, origin/fix/issue_41, refs/pull/origin/42) Fixed existing tests

$ git grep -n checkInteg
R/assign-test-ids.R:18:#' @importFrom checkmate assert_string checkIntegerish
R/assign-test-ids.R:28:  checkIntegerish(start_after, lower = 1)

$ git grep -n check_integ
NAMESPACE:16:importFrom(checkmate,check_integerish)
```

**Review by kyleam — CHANGES_REQUESTED** [review]

File: NAMESPACE (hunk 8 above)
Comment (barrettk) [reply NAMESPACE:16]: @kyleam actually, for some reason it appears some of the changes I made got reverted accidentally. Just noticed one of the other changes I made got undone as well.

File: tests/testthat/test-assign-test-ids.R [hunk 9]
```diff
@@ -97,5 +98,40 @@ withr::with_options(
...
+
+    test_that("test name string is repeated in a non-testthat() environment", {
+      skip_if_over_rate_limit_github()
+      skip_if_no_github_pat()
+
+
+      test_ids <- assign_test_ids(prefix = "MRGVAL", overwrite = TRUE)
+
+      fake_test_path <- file.path(getOption("mrgvalprep.TEST_LOC"), "new_tests", "test-repeated-text.R")
+      fake_test <- parse_tests(fake_test_path)
```
Comment (kyleam) [inline tests/testthat/test-assign-test-ids.R:128]: This test isn't actually serving as a regression test for gh-41 because it will still pass with `replace_test_str`s old regex.  `parse_tests` had a more specific regex before this test, so you won't be able to detect the problem if `parse_tests` is collecting the tests.

```
$ git show --oneline -s
ab60d99 (HEAD, origin/fix/issue_41, refs/pull/origin/42) finished restoring previous changes, added test for issue 41, and fixed other tests
```

Revert regex change from a69f336:

```diff
diff --git a/R/assign-test-ids.R b/R/assign-test-ids.R
index 098a74c..d535fcf 100644
--- a/R/assign-test-ids.R
+++ b/R/assign-test-ids.R
@@ -222,7 +222,7 @@ print_and_capture <- function(x)
 #' @importFrom stringi stri_replace_all_regex
 #' @keywords internal
 replace_test_str <- function(test_file, from, to){
-  from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *['\"])")
+  from <- paste0("(['\"] *\\Q", from, "\\E)( *['\"])")
   to <- paste0("$1 [", to, "]$2")

   test_file_new <- stri_replace_all_regex(test_file, from, to, vectorize_all=FALSE)
```

Tests still pass:

```
$ Rscript -e 'devtools::test(filter = "assign-test-ids")'
ℹ Loading mrgvalprep
ℹ Testing mrgvalprep
✔ | F W S  OK | Context
✔ |        12 | assign-test-ids [10.2s]

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 12 ]
```

However, that does leave unstaged changes in `inst/fake-tests/new_tests/test-repeated-text.R`, so the regression would probably be noticed, but "leaves my working tree dirty" of course isn't a great test assertion.

<details>
<summary>diff</summary>

```
$ git diff -- inst
diff --git a/inst/fake-tests/new_tests/test-repeated-text.R b/inst/fake-tests/new_tests/test-repeated-text.R
index e61a102..0798dfa 100644
--- a/inst/fake-tests/new_tests/test-repeated-text.R
+++ b/inst/fake-tests/new_tests/test-repeated-text.R
@@ -1,16 +1,16 @@
 context("Fake Test - repeated text")

 test_that("Fake test with same text repeated [MRGVAL-TEST-0098]", {
-  str <- "Fake test with same text repeated"
+  str <- "Fake test with same text repeated [MRGVAL-TEST-0098]"
   expect_true(is.character(str))
 })

 test_that("Fake test with same text repeated [MRGVAL-TEST-0098]", {
-  str <- "Fake test with same text repeated"
+  str <- "Fake test with same text repeated [MRGVAL-TEST-0098]"
   expect_true(is.character(str))
 })

 test_that("Fake test with same text repeated 2 [MRGVAL-TEST-0099]", {
-  str <- "Fake test with same text repeated 2"
+  str <- "Fake test with same text repeated 2 [MRGVAL-TEST-0099]"
   expect_true(is.character(str))
 })
```

</details>

One way to improve the situation would be to overwrite in a temp directory copy and then compare to the tracked golden file ([my related comment from pr 36](https://github.com/metrumresearchgroup/mrgvalprep/pull/36#discussion_r843290661)).

I'll leave it up to you whether you want to try to address this.

File: R/assign-test-ids.R [hunk 10]
```diff
@@ -116,25 +121,35 @@ milestone_to_test_id <- function(stories_df, tests){
...
-  tmp <- str_match(lines, re) %>%
-    `[`(, "name") %>%
-    discard(is.na) %>%
-    str_trim(side = "both")
-  setNames(tmp, rep(basename(test_file), length(tmp)))
+    test_names <- str_match(lines, re) %>%
+      `[`(, "name") %>%
+      discard(is.na) %>%
+      str_trim(side = "both")
+  setNames(test_names, rep(basename(test_file), length(test_names)))
```
Comment (kyleam) [inline R/assign-test-ids.R:152]: nit: lines 148-151 are over-indented

**Review by kyleam — APPROVED** [review]
A couple of comments, but none are blockers

**Comment by kyleam** [comment]
Note that tightening this regex also fixes #40
